package frames

// This is the value stored in the FrameMap
var samuri = DefaultFrameType(samuriFrames)

var samuriFrames = []string{
	`
xxxxOXXXXXXXXXXXXXXXXXx.             .'''''.      ckkkkkkkkkkkOXWWWWNNWWWWWWWWWWWWWWWNNNWNNNNNNNNNdcxkkkkOd;.            .okkkkkkkkkkOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNX0Ol.           .odoox0XK0Okkxxxxkc.          ,0NNNNNNNNNNNNNNNNNNNNNNNNk;,;,.      .xXXXXXNNNNNNNNNNNNNNNNNNNXNNXNO'        'cccc
xxxxkKXXXXXXXXXXXXXXXXx.             .'''''.      ;kkkkkkkkkkkkKKKXNNNWWWWWNNNWWWWWWWWNNWWNNNNNNNNdckOkkkOx;             .cxddxkkkkOKNWWWWWWWWWWWWWWWWWWWWWWWWNXKK0KKKXXNNXOOl.           ,dollkXNNNXKOdodxk:          .lKNNNNNNNNNNNNNNNNNNNNNNNXd,,,;.      .dXXXXXXNNNNNNNNNNNNNNNNXXXK00KO'       .;cc::
xxxxkKXXXXXXXXXXXXXXXXO'             .'''''.      ,xkkkkkkkkkkxkkOKNNNNWWWWWNWWWWNXKKKKKKKKKKKKKXNxcxOkkkkk;             .:lldxkkkkxxk0KK000000KNWWWWWWWWWWWWKOxddxkOkkxxkkxdc.           ,dkkxdkXX00kdxkkkk;       .  ,kXNNNNNNNNNNNNNNNNNNNNNNNKl,,,;.       oXXXNNNNNNNNNNNNNNNNNNNXK0Okk0k'       .::;;;
xxxxk0XXXXXXXXXXXXXXXX0,             .'''...      .dkkkkkkkkkOKXNNWWWWWWWWWWWWWWNKOKXKKKKKKKKKK0KXxcxOkkkOk;             .ckkkkkkkxdookKXXNNXXKKXNWWWWWWWWWWWXKXNWWWWWWNXKxlol.           'dkkkxd0NXkoxkkkkx,       . .cKNNNNNNNNNNNNNNNNNNNNNNNNO:,,,;'      ,kKKKXXNNNNNNNNNNNNNNNNNX0O000KO'     . .;;:c:
xxxxxkOKXXXXXXXXXXXXXX0;             .'''...      .lkkkkkkkOKXXKKKXXNWWWWWWWWWWWWWWWWWWNNNWWWWWWWWxckOkkkkk:              ;kkkkkkkkkkO0OkOO00KKKXWWWWWWWWWWWWWWWWWWWWWWWWNOoxx.           .dkkkkkKXkdxkkkkkd.       . .dXNNNNNNNNNNNNNNNNNNNNNNNXd;,,,;'      ,O0000KXNNNNNNNNNNNNNNNNNNXK00Kk.    .'';cc;;,
xxxxxk0XXXXXXXXXXXXXXXK:             .''..'.      .oxxkOOkkkOkkxxkkOKWWWWWWWWWWWWWWWWWWNXXXXXXXNNNklkOkkkkOc    .         ckkkkkxxxxO0OdlodxdddddxxkkOO0KNWWWWWWWWWNNWWWWNKkkx'           'xkkkkkOxdkkkkkkko.       ..,ONNNNNNNNNNNNNNNNNNNNNNNN0c,,,,;,.     'k00000KKXNNNNNNNNNNNNNNNNX0O0Kx.    .;l:;,;:c
dxxddxkOOOKXXXXXXXXXXXXl             .'..''.       ...,:ldxdoodk0XNNNWWWWWWWNNNWWWWWWNX0KKXXXNNWWWklkOkkkkOo.             '::::;;;;;;;;;,,,,,,,,,,,,,,,,;codOKNWWWWWWWWWWWNKOd.           ,xkkkkkOkkkkkkkkkl.        .lKNNNNNNNNNNNNNNNNNNNNNNNXx;,,,,;,.     .x00000KKXNNNNNNNNNNNNNNNNNXKKKO'  .:l:.':::cc
dxxxxxkO0KKXXXXXkox0XXXo             ..''''.       .;clllloodxOXWWWWWWWWWWWWWNNWWWWWWWNXK0000KNWWWklkOkkkkOx'             ,olllcc::;'...''''',,;;;;;;,,;;,,,,:lkXNKOkdoollllc:..          ;kkkkkkkkkkkkkkkk:         .xXNNNNNNNNNNNNNNNNNNNNNNNKc',,'';;.     .d0KK00KXNNNNNNNNNNNNNNNNNNXK0KO,.cdd, .;:::::
oxxxk0KXXXXXXX0l. .:dkKx.            ..''''.       ,odddddxkkk0XNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOlxOkkkkOk,  .          ;kkkdlc;,'....''''',,;;;;,,,,,;,,,,,,,:c;,,,,,,,,,,,,,,'...     ckkkkkkkkkkkkkkkx,         ;0NNNNNNNNNNNNNNNNNNNNNNNNk;,,'. .,,     .o0KKKXXNNNNNNNNNNNNNNNNNNNNXXNx:ddc'  .;:::::
lkxxkKK0KXXXXX0o;,cxkxOk.            ..''''.       ,xkkkkxxxxkkkOOO0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOldOkkkkkk:  .          .c;,'..',,;;;;;;;;;,;;;;,,,,,,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,'....ckkkkkkkkkkkkkkkd.         oXNNNNNNNNNNNNNNNNNNNNNNNXl...    .'.    .dKXNNNNNNNNNNNNNNNNNNNNNNNX000c,;.    .::;:::
ckxxO00O0KXXXXXX0OOOKKXk.             .''''.       'xOkkkkkkkO0KXNNNWWWWWWWXK00XWWWWWWWWWWWWWWWWWWNdckkkkkkx:..           ..',,,,,,,,;;,,;,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,';cdkkkkkkxxddxkl.        .ONNNNNNNNNNNNNNNNNNNNNNNN0, .'...'',.    .kNNNNNNNNNNNNNNNNNNNNNNNNNXKXKc..     .;;;;;;
:kxxxkOOOKXXXXXXXXXXXXXk.             .''''.       ,kOkxdkOkk0KKXNNNWWN0Okxlc:ckXWWNNWWWWWWWWWWWWWNdlkkxkkxl,'..      ..'''.....',,,,,,,,,,,,,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,'':okkkkkdlloc.         .:d0NNNNNNNNNNNNNNNNNNNNNNd.  .,,,,;,.    'ONNNNNNNNNNNNNNNNNNNNNNNNNNNXNx.      ';;;;;,
;xxxdOXXXXXXXXXXXXXXXXX0,             .''''.       .cl,..cllooodk0KXWNOooxko:;;:ooxKNWWWWWWWWWWWWWOcdkkkkko;....     ...      .,;;;,,,,,,,,,,,,,,,,,,'',,,,',,;;,,,,,,,,,,,,,,,,,,,,,,,,,,;,;,',:dkkkkxddl.           .:kNNNNNNNNNNNXNNNNNNNNK:   .,,,,;,.     oXXXXXNNNNNNNXXXXXXNNNNNNNNNNNx.      ';;;;;,
,xxxx0XXXXXXXXXXXXXXXXXK:             .''''.           .;looddkKNWWNNNX0kdlc;;;:cclk00KWWWWWWWNWWWKloOkkkxlc:.              .,;,,,,,,,,,,,,,,,,,,,,,,'......';;;,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,,,cxkkkkkk,          .;;:KNNNNNNNNNXXNNNNNNNNO'   .,,,,;,.     cXNNNNNNNNNNNXKKKKXNNNNNNNNNNNk.      ';;;;,,
.dkxxOKXXXXXXXXXXXXXXXXXl             .''''.        .'lxkkkkkk0XNWWXXNXOdl:.  .';ldk0XNWWWWNWNNWWWNockkkkkxkd.            .',,,,,,,,,,,,,,,,,,,,,,,,'... ..,;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,;,';okkkkx'        .oKKkoOXNNNNNNNNKXNNNNXXNXd.   .,;,,::.     :000KNNNNNNNNNNNNNNNNNNNNNNNNNk.      ';,,;;,
.okxxkKK0KXXXXKKXXXXXXXXd.            .''''.        :kkkkkkkkkkk0NWWWNK0KNN0OOKK0KNNNWWWWWWNWWWWWWNockkkkkkko.           .,;,;;,,,,,,,,,,,,,,,...''''...',,;;;;,,,,,;,,,,,,,,,,,,,,,,;,,,,,;;;;;;,,,'cxkOx.        .kNNNNK0XNNNNNNNXXNNNNNNNK:    .,,,,:c.     cO0XNNNNNNNNNNNNNNNNNNNNNNNNNNO'      ';;;::;
.ckxxk0K0KXXXXK0XXXXXXXXk.            .''''.        .:kkxkkkkkk0KNWWWWNK0O0KNWNNNNWWWWWWWWWWWWWWWWNdlkkkkkxc.           .,;;,;;,,,,,,,,,,,,,,,'.     ..',,;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,;;;'.:xOd.        :KNNNNNNNNNNNNNNNNNNNNNNNk.     ,,,;;c'    .dOk0XNNNNNNNNNNNNNNNNNNNNNNNNN0,     .,;:::;;
 :kxxx0XKKXXXXXXXXXXXXXXO'            ......         .okodkkolxKNWWWNNWWWN0OOKNWWWWWWWWWWWWWWWWWWW0ldkkkko,.           .,;;;;;;,,,,,,,,,,,,,,,;;,.   .',;,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,'.;xd.       .xXNNNNNNNNNNNNNNNNNNNNNNXc      ';,;;:,    ;kkkkO0XNNNNNXNNNNNNNNNNNNNNNNNK:     .;:;:;;;
 ;xxxxOK0OO0KXXXXXXXXXXX0,           ..  ...         .dkxkkkxdxKNWWWNNWWWWWWNXNWWWWWWWWWWWWWWWWWWWxcxkkd;.           ..',;;;;;;,,,,,,,,,,,,,,,;,,,,'.';,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,.,:.       ;0NNNNNNNNNNNNNNNNNNNNNNNO'      ';,::;'    ckkkkkdONNNNXxONNNNNNNNNNNNNNNNK;     .;;;;;,;
 'xkxxOXXXXXXXXXXXXXXXXXK:           .......         'xkkkkkkkk0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWOcxkl'              ..,;;,'''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,;,,,'.       .dXNNNNNNNNNNNNNNNNNNNNNNNd.      ';;:cc;.   :kkkx;,xXNNNXxlONNNNNNNNNNNNNNN0'     .;;;;,;:
 .dkxxOXXXXXXXXXXXXXXXXXXc           .....           'xkkkkkkkkkkkKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKodo.              .','..''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,'''.      ;KNNNNNNNNNNNNNNNNNNNNNNNK;       .:;;c::.  .ckkd,..:kNNNkc,;0NNNNNNNNNNNNNN0'     .:;;;,;:
 .okxxOKXXXXXXXXXXXXXXXXXo           .....           .dOkxxkkkkkkk0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXdc,              .....',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;,'''.    .xNNNNNNNNNNNNNNNNNNNNNNNNk.       .:;;:::.  .dkko..:lkXNNk,':kNNNNNNNNNNNNNNO'     '::;;;::
 .lkxxkKXXXXXXXXXXXXXXXXXd.          ......          .oOkolxkkkkkOXWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWd'.              ...,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,'..'.   :KNNNNNNNNNNNNNNNNNNNNNNNXo        .;;;:;;. .ckkkkc,cdKNNN0;:0NNNNNNNNNNNNNNNO.     ,c::;;c:
  ckxxkKXXXXXXXXXXXXXXXXXd.          ........         ckkdcokkkkxOXWWWWWWWWWWWWWWWWWWWWNK0000KKXXKk,               .',',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;,,'...'..:0XNNNNNN0OXNNNNNNNNNNNNNK;         ,,,;;;. .,okkkd:l0NNNNXxkNNNNNNNNNNNNNNNNx.     ,c::::c;
  :xxxkKXXXXXXXXXXXXXXXXXx.      .    .'...'.         ;xOklokk0KKXNWWWWWWWWWWWWWWWWWWWWWWNKOkkkkkc.              .''...',,,,,,,,,,,',,,,,,,,,,,,,,,,,;,;;;,,,,,,,,,,,,,,,,,,,:c:,,,,,,,,,,,,,,,,,,,,;;;;;;,. ....,codxkxddOXNK0O0KXNNNNNNk.         ',',;;'   'dkkkkOXNNNNXXNNNNNNNNNNNNNNNNNd.     ,c:::cl;
  ;xxxkKXXXXXXXXXXXXXXXXNk.       .   .'''''.        .:xOkxxkkKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0l.              ...   .''',,,,,,'..','',,,,,,,,;;;;;;;;;;,,,,,,,;;;,,,;c:,,;:::;;,,,,,,,,,,,,,,;;;,,,;;;;;;,.  'llccccloxKX0OxdxkkxodOXNXl          ',',;;,.  .dkkkOKXNNNNNNNNNNNNNNNNNNNNNNNl     .;cc:cll,
  ;xxxk0XXXXXXXX00XXXXXXNO.           .'''''.        ,lxkkkkkkxOXWWWWNWWWWWWWWWWWWWWWWWWWWWWKx;.                      ....',;,'.  ','.',,,,,,',,,;,,,;;;;,,,,,,,;:cll::lol:;,,,,,,,,,,,;,,,,,'',;;;;,;;;,',;;..:XNNNNNNNNNNNXXKOOkx;..lKk.         ..,,,;:;.  .oOkO0KKKXNNNNNNNNNNNNNNNNNNNNXc     .:ccccll,
  ,xxxk0XXXXXXXXXXXXXXXXN0'           .'''''.        'okkkkkxk0XXNNWWWWWWWWWWWWWWWWWWWWWN0x:.                           .',,..   .''..',',,''''.....''',;,,,,,,,,,;:cc:;;cc:,,,,,;;,;,,;;,;;;,'..,;;,,;;;,..,,''dXNNNNNNNNNNNNNNK0K0dlxKl...       ..,,,;;;.  .lOkkOKXXXNNNNNNNNNNNNNNNNNNNNX:     .:ccllll'
  'dxxx0XXXXXXXXXXXXXXXXX0,           .'''''.         .ckkkod0XX00XWWWWWWWK0KNWWWWWNX0xc,.                              .'..    ....  ...,,. ..     ....',,,'..'..,,,,;,,,,,,,,,'',,;,,'',,;;;;,...'''',;;,...,,,oKNNNNNNNNNNNNNNNNNNNN0:...       ..,,,;;;'  .lkkO0KKKXNNNNNNNNNNNNNNNNNNNNX:     .clllllc'
  .oxxx0XXXXXXXXXXXXXXXXXK;           .'''''.    .     ;kOxodOOkkKNWWWWWWWXOkxdl::;'..                                          .       .',.         .,. .''.. .  ...''''.',,,,,,,''',;,''',,,,;;.   ...',;,. .',,;oONNNNNNNNNNXXXXXXXN0' ..       .',,,,;;,. .lkkO00KKXNNNNNNNNNNNNNNNNNNNNK;     'clllllc.
  .okxkKXXXXXXXXXXXXXXXXXX:           .'''''.     .   .okkxldkkkKWWWWWWWWWWWWNXOo;..                                                     .'.  ......  ..   ...          ......''',;;,',;;,'....',;'.   ...';,.  ..'',cdOKXNNNNXXXXXXXNXo  ..       .......... .lkkkOKXNNNNNNNNNNNNNNNNNNNNNNO'    .,llllllc.
  .lkxk0XXXXXXXXXXXXXXXXXXl      .    .'''''.     .   'xOkkxxkkkOKXWWWWWWWWWWWWWWWXOxolc:::;''.                                          .'. ,kxxOx;                           ..'.',;''',;,..  ..''.     ..,,.   ......,:cldkOKNNXXXN0;  ..        ......... .lkkkO0KKKKXNNNNNNNNNNNNNNNNNNO.   ...:lllllc'
  .lkxxOKXXXXXXXXXXXXXXXXXo      .    .'''''.          cOkkkkkkkkxONWWWWWWWWWWWWWWWWWWWWWNOxl,.                                           .. lKKKK0o.                            ....',,...',,.   ..'.      .''   .ckxxxxkkO0KXXNXXXXNx.   ..       .,,,,;;,. .lkkkxdx0NNNNNNNNNNNNNNNNNNNNWO.  .'.,cllllll:
  .ckxxOKXXXXXXXXXXXXXXXXXd.     ..  .'''''''.        .ckkkkkkkkkkkOKWWWWWWWWWWWWWWWWWWWKxo:.                                             ...oKKKKKO;                              .'..',.  ..,.     ..      ...   .dXNNNNNNNNNNNXXXNK:    ..       .,,,;;;,.  ckkkxkKXNNNNNNNNNNNNNNNNNNNNWk.  ',':lllllll;
  .ckxxkkOXXXXXXXXXXXXXXXNd.      . .''''''''.        .lkkkkkkkkkkkx0NWWWWWWWWWWWWWWWWN0dl'                                               ...oKKKKKKx.                               .'....    .'.     .       ..   .xNNNNNXXXNNNXXXNO.     .       .,;,,;;'  .ckkOKXNNNNNNNNNNNNNNNNNNNNNNNk. .:,.:lllllll'
  .ckxxk0XXXXXXXXXXXXXXXXNx.      ...''''''''.         :kkkkkkkkkkkOXWWWWWWWWWWWWWWWWW0l;.                                                 ..lKKKKKKKd,. ..                            .'..     ...             .    'ONXNNNNNXXXXXXNd.     ..       ';,,,;'  .ckO0KXNNNNNNNNNNNNNNNNNNNXXXNk..,:'.:ollllol.
  .ckxxxOK0KXXXXXXXXXXXXXNk.      ....'''''''.        .ckkkkkkkkkkOXWWWWWWWWWWWWWWWWWK:.                                                    .c0KKKKKKK0o..'.                             ..                           cXNXXXXXXXXXXNK;      ..       ';,,,;'  .ckO0KXNNNNNNNNNNNNNNNNNNNNNNNx..::..:olllloc.
  ,dxxxxxxx0XXXXXXXXXXXXXNO'      .....''''''.        :kkkkkkkkkkk0NWWWWWWWWWWWWWWWWXl                                                       ,kKKKKKKKKKd..'.                             ..                        '.,KNXXXXXXXXXXNk.   .           ';,,,;'  .ckkkO0KNNNNNNNNNNNNNNNNNNNNNNk,,:, .:ollllo:.
  :xxxxxk00XXXXXXXXXXXXXXXK;       .. .,''''.         :xkkkkkkkkkOXNWWWWWWWWWWWWWWWNd.                                                       .oKKKKKKKKKKx,..,.       .,'                                           ;:;0NXNXXXXXXXXXl    .           ';,;;;,  .ckkkO0XNNNNNNNNNNNNNNNNNNNNNNk;;;.  ;ollolo; 
  .:xkxx0XXXXXXXXXXXXXXXXXXc      ... .,''''.          ckkkkkkkkOXWWWWWWWWWWWWWWWWW0'                                            ..           ;kKKKKKKKKKK0l..;:.      .lo,.                                        colKNNNXXXXXXXN0,              ...,;;;;,.  cOOOO0XNNNNNNNNNNNNNNNNNNNNNNx;;.   ;oooooo, 
   .oxxxO000KXXXXXXXXXXXXXXl      ..  .'',,,.         .okkkkkkkxOXWNWWWWWWWWWWWWWWNl                                .     ..     ..           .l0KKKKKKKKKKKkc',lc.     .cd:.                                    ...doxNNNNXXXXXXXNx.             .c'.,,,;;,.  :O0KXNNNNNNNNNNNNNNNNNNNNNNNNx;,.   ;oooooo, 
    ;xkxkkkkOOKXXXXXXXXXXXXd.      .  .''',,.         'xkkkkkkkkk0OOOKNWWWWWWWWWWWO.  .,.                          .:.    .;'     :;           ,dOO0KKKKKKKKKKOl;cdc.      ....                ..                .'cxkXNNNXXXXXXXXXl      .      .::..;,,;;,.  :kO0XNNNNNNNNNNNNNNNNNNNNNNNNx,.    ,oooooo, 
    ,dkxOKNNk;:OXXXXXXXXXXNx.         .'''',.         .dkkkkkkkxxxxxxxOXNWWWWWWWWWo  .c'                           .:'     ;d'    ,x:          .;k00KKKKKKKKKKK0x;..       .ckOd;.          .:dxdo:.             'o0KXNNNNXXXXXXXN0,      .      'c. .;;;;;;.  :kkkOKNNNNNNNNNNNNNNNNNNNNNNNk.     ,oooooo, 
    ;xkxkKNXo''cKXXXXXXXXXX0,         .'''''.         .dOkkxodkddkxxxxkkO0NWWWWWWX: .c:                            .,.     .;:.   .oO:.          c0KKKKKKK0Oxl:'.   .','.  .o0000xc'.      .dOd:',oo.           .dXNNNNNNNXXXXXXXNx.            .:;. .;;;;;;.  ;kkkOKXNNNNNNNNNNNNNNXNNNNNNNd.     ,oooool' 
    'dkxk0X0kl:o0XXXXXXXXXXXl         .'''''.         .dOkOxlokkkkkxxxxxxkKWWWWWWK; ;o.                            'o; ',.         'dx:,'         c0KOkdl:'.       .,::;'.  .;cx0000o.     :d;..,,lOc          .oXNNNXXXXXXXXXXXNXc       .     .:.  .;;;;;;.  :kkO0KNNNNNNNNNNNNNNNXNNNNNNXc     .;oloool' 
    .dkxkOOOK0k0XXXXXXXXXXXXk.        .'''''.         .oOkOxcokkkkkkkkkkxkKWWWWWWX;.o:                              cd'.lo;.        .'''lo'       .;;...    ...          .'.  :k0000O;     '',;ckdoOk'         ;0NXNNXXKKXXXXXXXN0,      ..     ;;.  .;;;;;;.  :kkOKXNNNNNNNNNNNNXKKXNNNNNNX:     .:ololol. 
    .okxxOKXKXXXXXXXXXXXXXXX0;        .'''''..        .oOkkkclkkkkkkkkkO0XWWWWWWWN:,d'                              .dx,.....'.      ....oko,.  .'..';;;;;col..:,       .;OO;:0000000o.     .,;lk000O;        .dXXXXXXXXXXXXXXXXNx.     ....   .;'   .;;;;;;'  ckkOXNNNNNNNNNNNNNNNXXNNNNNNK;     .coooloc. 
    .ckxxk000XXXXXXXXXXXXXXX0,        ......'.        .oOkkkclkkkkkkkkOXNK0KNWWWWWoll.                               'xxl;.:0NO'..     .',o00Odc;;:ccdkkkO00olONKl,'. ..;ON0xO000000Kx.     .:c;l0000c        .dXXXXXKKXXXXXXXXXXl      .;;,.  .,.   .;;,,;;' .ckkkKNNNNNNNNNNNNNNK0KNNNNNNX:     'looolo:. 
     :kkxk00OO00KXXXXXXXXKXX0,       ...   ...        .dOkkkxxkkkkkkkkOKOxxx0NWWWWKk:                                 ;k0Ool0NNO;..    .;lodO00K0Oxk00O000000XNNWXx:,,;lOXOxk0000000Kk'   ,.'xxclkkOk,         ;0NXXKOOKK0xkKXXN0,      .;;;.  ..    .;;,,;;'..lOkkOKXXNNNNNNNNNNX00XNNNNNNX:     ,looolo;  
     ,xkxkO00KXXXXXXXXXXXXXX0,        .....',.        'xOkkkkkkkkkkkkkkkxxxkKNWWWWWX;                           ..     c0000KNNWKo,'..:Okk0OO000000K0000000KKKKXXK0Okxkkxolok0000000Kk,  ;d,,dolkolx:      ..   :0XXKOOKKd;';lOXo.      .;;;.        .;,,;;;,..lOkO0XXNNNNNNNNNXXX0OKNNNNNNK;     ;olllll,  
  .  'dkxxkKXXXXXXXXXXXXXXXX0,        .''''',.        'xkkkdoxkkkkkkkkkkkxxk0XWWWWWX;    .                     'l' ..  .d000kdkKNNKOkOKXKKK0000000000K00K000KKKK0OxddddxxkO0000000000k'.;c'.lolxolo;       ....  'xXNNNX0OxodxOO,        ,:;.       .','',,,,..oOkO0XNNNNNNNNNNX0O0XNNNNNNNX:     ;olllll,  
 ... .okxxk0XXXXXXXXXXXXXXXX0,        .'''','.        ,xkkklcxkkkkkkkkkkkkkxx0WWWWWNl   .,      .         ... 'dx. ';.  ,k000xodxxkkO00000KK0000000000000KKK000000000000OOkkkkOOOOOO0x;''.';llccoo'         .:kd:'':dk0XX0OOKNNd.        ';;'       ........,..oOkk0XNNNNNNNNNNNNXO0NNNNNNNX:    .:oollll'  
 .,. .lkxxkKXXXXXXXXXXXXXXXX0;        .'''','.        ,xkkkcckkkkkkkkkkkkkkkOXWWWWWW0'  c;     ..       .;::''dkc   ,:.  c00000000000000000KkdO0000000KK00KK0000000000OOkkkkkOOOOOOOOxl:,,cdOkod:.           ,0NNX0Okk0XXXXXXNX:         .;'.       ..,;;,,;;.'oOkO0XNNNNNNNNNNNNNNNNNNNNNNK;    .cc;;;;c,  
 .;.  ckxxkKXXXXXXXXXXXXXXXXK:        .''',,'        .;xkko.:kkkkkkkkkkkkkxkKWWWWWWWWx..d;    .'.      .llol,okx,    ,l:.'d000OOkkkO0000000KdcdxxkO0000000KKK00000000000000OOOOOOOOOOkkkdx0KKOo.             .kNXXXXXXXXXXXXXNO'         .'''.      .',;;;;;;',dOkO0000KKXNNNNNNNNNNNNNXXXNK;    .lccclllc. 
 .,'  ;xxxk0XXXXXXXXXXXXXXXXXl        .,,,,,.       ..,dOx'.cdkkkkkkkkOOOO0XNWWWWWWWWNo:k;    ,,      'ddod:lkkx'     'lo;ckxdddxkO00000000OccxxkkO000KK00KKK000000000000000OOOOOOO00kdkK00Oo'                oXXXXXXXXXXXXXXXd.         .,:,.       .,;;;;;,'':c:lkKK0KK0000000XNNNNNNXXXNK;    ,llllllll, 
 .''  ;xxxxkKXXXXXXXXXXXXXXXXo        .,,,,,.       ..,xk:.:dldkkkkkk0XXXXNWWNNNWWWWWWXkkc   .c.     'xkdkdcdkkx'      .;:':lokO00000000000olk0000000KKKKKKKKKKK00000000000OOOkkO0000c..;;'.                  ,0NXXXXXXXXXXXX0:           .:,.       .,;;;,...''';:cld0XKKXXXXXXXNNNNNNNNNNK;   .;ollloool, 
 .,'. ,xxxxOXXXXXXXXXXXXXXXXXx.       .'',,,'       ..;kx'.okdldkkkkkOOkxkO0KKKNWWWWWWWNXk.  ;c     .lOkkkxldOkx,          .okO0000000000Kkld00000KK000KKK000KKK00000000000OOO0OO000x'                         lXXXXXXXXXXXXXk'           .,'.       .,;;....,;coxxxo:cxKNNNNNNNXXXXXXXXNXNXc   .:c'..,col' 
 .;,. 'dxxxkKXXXXXXXXXXXXXXXX0,       .,',,,'      ...ckx, 'cdddkkkkkkkkxkO0KXWWWWWWWWWWWNd. c:   .lcokkkkkodkkk,           cOO000000000000kodO00dlx00000KK0KKKKKKK000000000OOOO000O:.:lc,                     .xXXXXXXXXXXXXo             ..        .''. ...;dxxxddddo:ckXNXXXXXXXXXXXNKol0l    ;:...;col. 
 .,,. .okxxOK0OO00XXXXX0OXXXXK;       .,,,,,'      ...lkx, .:oxkkkkkkkkkO0KKXWWWWWWWWWWWWWNd'c,  .okxoxOkkkxdkkk;           .d0000000000000K0xx00kkO0K00KKKKKKKKKKKKKKK0000000OO000l,o00Kx.                 ... 'kXXXXXXXXXNKc              .        ........',cdddddddxl;xNXKKXXXXXXXXNk. :c.   'lllloooc. 
 .,,. .lkxxO00O00KXXXXXKKXXXXXl       .,,,,,'      ...lkx, ...:xkkkOKK0OOKXXxco0WWWWWWWWWWWNkl'  :kOOoxOkkkkkkkk:            'x000000000000K00KKKKKKKK00KKKKKKKKKKKKKKKK000000000KOxk000K0;                  ;d:';kXXXXXXXXNO;.             .        .''....',..,:oddddc,'dXX0OXXXXXXXXNKl.,o;   'llloooo:. 
 .;;. .lkxxO0O00XXXXXXXXXXXXXXd.      .,,,,,'.     .  ;kx,.,:lxkkkk0NNKKNXx:,. ;0WWWWWWWWWWWNO'  oOOKddOkdccdkkk:             'x0000000KKKKKKKKKKK00KK0KKK0KKKKKKKKKKKKKK00K0000kx0KK00K0Kd.                 .xNKOOKKXXXXXNXx.             ..      ..'',''..',,..'':l;''cOXNNXXXXXXXK0KXXXKKX0,  'llloooo:. 
 .;;'  ckxodOKXXXXXXXXXXXXXXXNd.  .   .,,,,,..      . .ox,,dc:okkkkKNWNXOd:.. .oNWWWWWWWWWWWWNk' oOkKddOkl,,cxkOc              .lO0000KKKKK0xdk0K0OOkkkkkxxOKKKKKKKKKKKKKKKKKKkc:x0KK0KKKK0:          .c,     oXXXXXKOkOOkKKl.             ..   ...''...''....,'.'.  'lOKK0KKXNNXNXX0dc;cOXNNK:  .coloooo;  
 .;;'  ;l::coOXXXXXXXXXXXXXXXXx.  .   .'',,'..      .  :k:;xOxdkkkOXNWXkol:.  ,0WWWWWWWWWWWWWWW0;:OK0xdkkd. :kkOl                ,d0K0KKKKK0OO0KK00000000kxOKKKKKKK000KKKKK0kc':kK0OO0KKKKKx.         .o0x;.  ;KNXNNNXOdxx0k:.             .. .','.....',''''.... .;dOKKKKKKXXNNNNNNNNKkodKNNk.  .:oloooo,  
 .;;'  'lol:;;xXXXXXXXXXXXXXXXx.  .   ..',,''.      .  :ko;oOkkkkkkKWWN0dc,.  oNWWWWWWWWWWWWWWWWXxOX0dokkkooxkkOl.                 ,oOK0KKKKKKKKOxdxO000000KKKKKK0K00KKKKOd;.'o0KK0O0KKKKK0x;.. .'   . .:oxkxxxKNNNNXXNXO0Xd'.             ...',,,'..'.';;;;,.. .:xKKKKKKK000KXNNNNNNNNNNNXNXc   .coooooo,  
 .;;'  'ddloookKXXXXXXXXXXXXXNk.  .  .'...'',.     .   ;kkcckkkkkkk0NWWXkl:. ;KWWWWWWWWWWWWWWWWWWWWKOddkkkkkkkkOo.                 .,:lk0K0KKKKK0xodk0000000000000KKKK0kl' .:kKKK0O00KKOxolccl:.,:.     .;:cONNNNNNXXXKXNN0c.           ..',,,'.',,'..'',;'.  .cxkO0KKXXXNNNNNNNNNNNNNNNNNXN0,   .coooooo,  
 .;;.  .dkxxxk0XXXXXXXXXXXXXXNO'  .  .......''     .   'xOl:xkkkkkkOKNWNKK0,.kNXNWWWWWWWWWWWWWWWWWWKkddkkkkkkkkOo.           .     cd:;:cdOK000KKKKKK00000000000K0KKOd;.  ,x0KKKOk0KOxocccloooollc.      .ol,xXNNNXXXXXKXNx,.         ..,'.'..'..'''''.... ...,xkOKXXXNNNNNNNNNNNNNNNNNNNNNNk.   .:oooool'  
 .;;.  .okxxxOKXXXXXXXXXXXXXXX0,     ..   ..''         ,xklcxkkkkkkkkOKNWWNdoKXNNWWWWWWWWWWWWWWWWNW0dddkkkkkkkkOd.          .;,   'xkxxdc;:lk000KKKKKKKKK0KK0KKKK0xc'   .o0KKK0Oxkxocclooooooooool,     'oKXl'dNNNXXK0OKNKc'.      ..''....,,..'.,;;,'. ..';;.,kkkkO00KNNNNNNNNNNNNNNNNNNNNNd.   .:oooooo,  
 .;;.  .ckxxxkKXXXXXXXXXXXXXXXK;     .'''..','.        ;kkookkkkkkkkkkk0NNX0kKNNWWWWWWWWWWWWWWWWWNWOdxxkkkkkkkkkx'           ;xl,.;loxxdddollod0KKKKKKKKKKKKKK0kl,.   .cOKKKKKxllcclooooooooooooool' .:xKNNNK;,0NXNNXXKKNO;'     ..'''''...';,'..',.. .';;;:;.,kkkkO0XNNNNNNNNNNNNNNNNNNNNNXl     ;oooooo,  
 .;;.   :xxxxkKXXXXXXXXXXXXXXXK:     ..''''',.         ;kxclkkkkkkkkkkkk0OO0x0WWWWWNNWWWWWWWWWWWWNWXxdxxkkkxdddxx:           ,xkxodxxxdodk0XNO:;okO0000000Okdc,.     ,x0KKKKOo::cloooooloooooooooc:coONNNNNNNx.lXNNNK00XNo'.  ..''.',''..''..',,'..   ,:;;;:,.,xkkk0NNNNNNNNNNNNNNNNNNNXNXNK:     ;oooooo,  
 .,;.   'dxxxkKXXXXXXXXXXXXXXXXc      .''''''.         ;kx:lkkkkkkkkkkkkO0XXOKWWWWWWWWWWWWWWWWWWWWNW0dxkkkkxoc::ol.          .dkxxkkkkkxdkKN0dl:....'''''...       .o0KKK0koccloooooooooooooool::lxKNNNNNNNNNK:,0NXNNXKXK:. ..''''..',,,.';;,''.     .,::;;:;..oOkkO0XNNNNNNNNNNNNNNXXXXXXN0,     ;oooooo,  
 .,;.   'xkkxkKXXXXXXXXXXXXXXXXl      .''''''.         ;kx:lkkkkkkkkkkkkKNWNNNWWWWWWWWWWWWWWWWWWNWNW0dkOkkkoccodxd'          .lkkkkkkkkkxk0dll,                  .:kKKKOdlccloooooooooooooooc:cdONNNNNNNNNNNNNk,cKNXNNKx;..','.........''',;'.        ,::::::,.:kkkkOKNNNNNNNNNNNNNNNNNXXXNO.    .:oooooo;. 
 .,;'   ,xkkkxOKXXXXXXXXXXXXXXXd.     ',''','.         ,kx:lkkkkkkkkkkkkOXWNWWWWWWWWWWWWWWWWWWWWWWNNkk0kkkko:coxkx,           ;xkkkkkkkkkoll;.                 .;x0KKOdcclolloooooooloololc:lxKNNNNNNNNNNNNNNNNO;:k0kl,.',;;;;'..'''','''...         .;::::::,.ckkkk0NNNNNNNNNNNNNNNNNNNNNNk.    .coooooo;. 
 .,;'   'dkkkxkKXXXXXXXXXXXXXXNx.    .','',,.          'xx:lkkkkkkkkkkkkkOKNWNNWNWWWWWWWWWWWWWNWWNWXxOKkkkkxddkkkx,           .dkkkkkO0dclc.                  ,d0K0OocclolooooooooooooolccdOXNNNNNNNNNNNNNNNNKOXO,.:'  .''''',,'..',,,,.             .;::::::,'oOkkkOXNNNNNNNNNNNNNNNNNNNNNd.    .coooooo,  
 .,;'   .okxxxOKXXXXXXXXXXXXXXNO'    .',,,,,.          .dx:ckkkkkkkkkkkk0KXNNNWNNNNNNNNNNWNWWWWNNNWOxXKkkkkkkkkkkx,           .okkkkkdclo,                  'o0K0OocclolooooooooooololclxKNNNNNNNNNNNNNNNNNKkx0Kx;;ll;.......'........    .  .       .;::::::,,xOkkkOXNNNNNNNNNNNNNKXNNNNNNo.    .coooooo,  
 .','.  .lkxkk0XXXXXXXXXXXXXXXX0,    .',,,,,.          .dk;ckkkkkkkkkkkkOKNWNNWNXXNXKKXNNNXKKKKKXWNkOW0xkkkkkkkkkx,           .oxo:,';dl.    .      ';:,..,oOKKOocclooooooooooooooolclkXNNNNNNNNNNNNNNNNN0OOkxdc:cllll,''.....',.         .....      '::;;:::,:kOkkOKNNNNNNNNNNNNNNNNNNNNNXl     .:oooooo;. 
 .',,.   ckkkxk0XXXXXXXXXXXXXXXK;    .',,,,,.          .ok;:kkkkkkkkkkkkxkXNNNNWWWWWWWWNNWNNXXK000kd0WOdkkkkkkkkkk,        .  .'''.'od,            ,c::dOO000OdcclooooooooooooooolccxXNNNNNNNNNNNNNX0O0XKxdoc:clllllll::c.   ...    ...   ......    .'.....,;,ckkO0XNNNNNNNNNNNNNNNNNNNNNNXc     .:ooooooc. 
 .'...   ;xxxdx0XXXXXXXXXXXXXXXK:    .',,,,,.          .ox;ckkkkkkkkkkkkkkKNNNWWWWWNNNNNNWNXNNNWWNKxoOkdkkkkkkkkkk:       ...'..;;cxl.      .     ,c,. 'x00Odcclooooooooooooooolc:o0NNNNNNNNNNN0OkkkkOkoc:ccllllllc;,';cl:.        .',.   ......     .',,,;::,lkk0NNNNNNNNNNNNNNNNNNNNNNNNXc      ;ooloool. 
 .....   ,xxxxOKXXXXXXXXXXXXXXXXl    .',,,,,. .        .do'cOkkkkkkkkkkk0XNNNNWWNNNNNNNNNNXNWNNNNNWNxdddkkkkkkkkkkl.    .';:;',:;ok;       .     ,;.   .o0xcclooooooooooooooooc:o0NNNNNNNNNN0ocok0XNKdcclllllllc:;,,;:,;llc,.      .',.              .:c::coc;oOkOKKXNNNNNNNNNNNXNNNNNNNNNX:      ,loolodo, 
 .',,.   ,xkxxOKXXXXXXXXXXXXXXXXo   ..',,','  .        .oc.:xkkkkkkkkkO0KKKNNNNNNNNNNNNNNNNNNNNNNNWXkKkokkkkkkkkkd:...';clc,':;;xx'       .    ';,  .:lddc:cllloooooooooollol:lONNNNNNNNNNXx:lONNNXOlcclcllllllc:cllll:,,cllc'     .',.              .:c::cl::xOkkkOO0KNNNNNNNNXXNNNNNNNNNK:      .lollooo;.
 .,,,.   'dkkxkKXXXXXXXXXXXXXXXXd. ...,,'','           .::::okkkkkkkkkOOO0KNNNNNNNNNNNNNNNNNNNNNNNWKk0kokkkkkxo:,'';:clcl:,,:;cOd.          .,cc;;:oOkdl:clllloooooooooolol::xXNNNNNNNNNNNX0KNNNXOoccllllllllllllllllllc:;;:ll'..   .'.              .:cc:ll;:kOkkkkkkOXNNNNNNNXXNNNNNNNNNK;      .collooo:.
 .,,,.   .dkkkk0XXXXXXXXXXXXXXXNk. ...,,'',.            .;xocxkkkkkkkkkkkO0NNNNNNNNNNNNNNNNNNNNNNNNWKxddkkkd:,',:clllllc;,;:;oKo.        .,:llc,l0K0dc:cllloloooooooololc;'c0NNNNNNNNNNNNNNNNNKkocclllllllllllllllllllllll:;,:c,,:'. ..    ....      .:ccccc,ckkkkkkkkOXNNNNNNNNNNNNNNNNNNK,     ..:olloool.
 .,,;.   .okxkkKXXXXXXXXXXXXXXXNO' ...,'',,.            .lOxllxkkkkkkkkkkkk0KKXNNNNNNNNNXNNNNNNNNNNWXkxdxx:',:clccclclc,,c::kKo.       .,lllll,:O0xcclollllooooolooool:;,,dXNNNNNNNNNNNNNNNXkdlccllc::cllllllllllllllllllllc;'cc,;lc'.     .....     .:cccc:,lOkkkkkkkOXNNNNNNNNNNNNNNNNNN0'    ...:olloool.
 .,;;.   .lkxxOKXXXXXXXXXXXXXXXN0,  .',,,,,.            'dkkkl,lkkkkkkkkkkxxkOKNNNNNKKNNXNNNNNNNNNNWKxxxc,,clcccllclc:,:c;l0Nx.      .';lllll;'dxc:cllllllllllllooolc:::ckNNNNNNNNNNNK0KNKxl:cllll:'.;llllllllllllllllllllllc;,cc,;ll,..   .....     .:cccc:;oOkkOOOkkOXNNNNNNNNNNNNNNNNNNO.    ...;olloool.
 .,;;'   .ckxxk0XXXXXXXXXXXXXXXX0;  .,,,,;,.       .  ..;kkxkdcokkkkkkkkkkkOKXXNNNNNNNNNNNNNNNNNNNNWXxd:.;clcccllllc;,cc:xXXd.      ,:;cllloc..;;cllllolllllllllolc:cc:oKNNNNNNNNNXOOOKKxl::clllc;'',lllllllllllllllllllllllll:;;;;;cc,,;.......     ,ccccc;:kOkOdlkKKKXNNNNNNNNNNNNNNNNNNk.    ...;olloooo,
 .,;;'    ckxxxOXXXXXXXXXXXXKKKXK: .,;,,,;,.       .  .,,okodookkkkkkkkkkxkKNNNNNNNNNNNNNNNNNNNNNNNNNd'':lccllllll:,;c:cONXo.      ;c;clllll,..;lollllllllllllolc::lc;dXNNNNNNNX0kk0XNOc:clccll:,,;;clllllllllllllllllllllllllllc;,::,,',:;.....    .;ccc:c,:xOkkxdOXNNNNNNNNNNNNNXXXNNNNNx.    ...:olllooo;
 .,;;'    :kkxxOXXXXXXXXXXXXK0KXKc  ..,'..'.       .  .c;;xkkookkkkkkkkkkkOKXNNNNNNNNNNNNNNNNNNNNNNNk,,cl::clllll;':c:oKNKl.      ;c;:lllllc',collllllllllllllc::ll:;xNNNNNNNX0kkKNNXkccllllll;';:;:llllllllllllllllllllllllllllllc;;;:c:;cl:.      .:ccc:c,,dOkkkkk0XNNNNNNNNNNNXXKXNNNNNd.    . .collllc;'
 .,;;.    ;xkxxkKXXXXXXXXXXXXXXXXl ...,,....       .  .od;lkkolkkkkkkO0KXXK000KXNNNNNNNNNNNNNNNNNNNd',ll;,cllllc;,::ckXN0:       ,l;;lllllc;:llllllllllllllll:;cl:',kNNNNNXOx0KXNNNKdcclllllc,,cl::lllllllllllllllllllllllllllllllll:;;cllllll:.    ':ccccc'.oOkkO00KNNNNNNNNNNNNNNNNNNNNNo.   .. .cc,';ll:'
 .,;;'    ,xkkxOKXXXXXXXXXXXXXXXXl .'',;,,,.      ..   cx:ckkolkkkkkkO000OOKXXNNNNNNNNNNNNNNNNNNNNd.,ll;,:llllc,,::dKNXO;  .'. .'c:;llllc:;clllllllllllllllc:::,. 'ONNNNNXxoONNNNNKl:clllllc''cl:;cllllllllllllllllllllllllllllllllllc;;:llllllc;. .,::::c;.,xkkOKXXXXXNNNNNNNNNNNNNNNNNNNo    .. .:lcclooc.
 .,,;'    'dkkxOKXXXXXXXXXXXXXXXXo..,;;;,,,.     ...   ckddkkdlxkkkkkkkkkk0NNNNNNNNNNNNNNNNNNNNNNx..cl:,:llll:,,;cOXNXk'  ';. ';::;clllc;:llllllllllllllll:::'.  'ONNNNXOxkKNNNNN0l:llllllc'.clc,:lllllllllllllllllllllllllllllllllllll:,:lllllllc;..,:;',..ckkkkO0KKKXNNNNNNNNNNNNNNNNNNXl    .. .:ooooooc.
 .'','    .okkk0XXXXXXXXXXXXXXXXXd..,;;;,,,.   .....  .lkkxxkdlxkkkkkkkkkkk0KXNNNNNNNNNNNNNNNNNNk..:l:,:llll:,;;oKNXXx. .;;..:l::;;lll:;clllllllllllllllc::;....'kNNNNNX0XNNNNNN0l:lllllll,.,ll;;cllllllllllllllllllllllllllllllllllllllc;;clllllllc'.';;,..lOkkk0KXNNNNNNNNNNNNNNNNNNNNNXl    .. .cooooooc.
 .'','    .lkxk0XXXXXXXXXXXXXXXXNk..,;;;,;'     . ..  .lkkllkxoxkkkkkkkkkkkkkk0XNNNNNNNNNNNNNNNO'.;l:,:lllc;,,:kXXXXd. .::';ll:::;coc;:lllllllllllllllc::;'.'cc:xNNNNNNNNNNNNNNKl:lllllll;..;l:',llllllllllllllllllllllllllllllllllllllllc;;cllllllll;..;:..okkkkkkOXNNNNNNNNNNNNNNNNNXXNXc   ... .looooooc.
 .;;;'    .lkxk0XXXXXXXXXXXXXXXXNO'.,;;;;;'     . ..  .lkxclkxodkkkkkkkkkkkkkxxOXNNNNNNNNNNNNN0; 'l:,;lllc;,;cOXXXKo. .:lclllc::;:oc;:llllllllllllllc:;;,';loc;xNNNNNNNNNNNNNNXo:cllllll:. .;::',cllllllllllllllllllllllllllllllllllllllllc,;lllllllllc'.'.,xkkkkkk0XNNNNNNNNNNNNNX0KNNXNK:    .. .loooooo:.
 .,;;'     ckkkOKXXXXXXXXXXXXKkx0O,.,;;;;;'    .  ..  .lOd:okxlokkkkkkkkkkkxk0KXNNNNNNNNNNNNNK: .cc';cllc;,;l0XXXKc  .;llllll:::,cc;:llllllllllllllc;,;,:lool:oXNNNNNNNNNNNNNNk:cllllllc,...;c,'cllllllllllllllllllllllllllllllllllllllllll:,:lllllllllc,..:kkkkkkkOXNNNNNNNNNNNNNNKO0NNNK:     ..'loooood:.
 .,;;'     ;xkkkKXXXXXXXXXX0o:;:lc..,;;;;;.       ..  .lOo;okklokkkkkkkkkkkkkOXNNNNNNNNNNNNNXl  ;l,,cllc,,;oKXXX0:   'llllllc;:;;c;cllllllllllllll;,:ccloooo:lKNNNNNNNNNNNNNN0:,clllllll:,..;,,cllllllllllllllllllllllllllllllllllllllllllll;,cllllllllll:.'lkkkkkk0XNNNNNNNNNNNK0XNNNNNNK:    .,''looododc.
 .;;;'     ,xkkk0XXXXXXXXKd;,:coo:;;,,;;;;.       ..  .lOo;okkookkkkkkkkkkkkkkOKNNNNNNNNNNNXo. .c,':llc,';oKXXXK:   .:llllll:::;;;clllllllllllllc;;loooooooccONNNNNNNNNNNNNNKl;,;lllllllc;..,,clllllllllllllllllllllllllllllllllllllllllllllc,;lllllllllllc'.ckkkkkOKNNNNNNNNNNNKKXNNNNNNK;    .:''looooodc.
 .;;;,     'dkkk0XXXXXXXO:';:c:;:ccc:'';;;.       ..  .lOd,ckkdlxkkkkkkkkkkkkkOKNNNNNNNNNNXo. .;,.;llc,';oKXXXKc    ;lllllll::;.;clllllllllllllc;:lollllloc:kNNNNNNNNNNNNNNXd:c;,clllllll:'',:lllllllllllllllllllllllllllllllllllllllllllllll;,clllllllllllc,.ckkkkk0NNNNNNNXXNNNNNNNNNNN0;   .;c''looooodc.
 .;;;,.    .okxk0XXXXXKd,,::;;,..';;;,.,;;.       ..  .lkl.;kkxoxkkkkkkkkkkkkOXNX0KXXNNNNKc   .'.,llc,';oKXXXKl    'lllllllc;:''clllllllllllll:;clllllllll:oXNNNNNNNNNNNNNNkcclc,,cllllll;',;lllllllllllllllllc::llllllllllllllllllllllllllllc,;llllllllllllc'.lkkkk0NNNNNNNXKXNNNNNNNNNN0,   .::.'looooodl.
 .;;;,.    .okxkOXXXXKl';c;'.......l00o;','        .  .co;.;kkkkkkkkkkkkkkkkxOKKkxxkk0XNKc..  . .cll,'::xXXXKl.   .:lllllll:;,,clllllllllllll:;clllllllloccONNNNNNNNNNNNNN0lclllc,,cllllc;';cllllllllllllllll;,;';llllllllllllllllllllllllllll:,:llllllllllllc..okkOXNNNNNNNNNNNNNNNNNNXNO,  .;c;..looooool'
 ';;:,.    .okxkOXXXKc':c,..'''..;ld00xxxc,.       .  .;:;'lkkkkkkkkkkkkkkkkkkkkxxkkkOXNx.',   .;ll;.;;:kXXXo.    'llllllll;.;clllllllllllll;;cllllllllll:oXNNNXXNNNNNNNNXd:lllllc;:llllc,.:llllllllllllllll:';l,,cllllllllllllllllllllllllllll;,cllllllllllll:.'dk0XNNNNNNNNNNNNNNNNNNXNO'  ':c' .cloooool,
 ';;:,.    .okxkOXXX0;.:,...''..cl..loo0XOo,.     ..  .:d;,dkkkkkkkkkkkkkkkkkkkkkOKXXXN0:':.   .cl;.',:OXXXx.    .:llllllll,.clllllllllllll::lllllllllloc:ONXNXXNXXXNNNXNOccllllllllllllc,,clllllllllllllllc''cl,,cllllllllllllllllllllllllllllc,;lllllllllllll:.,xKXNNNNNNNNNNNNNNNNNNNNk' .,cc' .cooooool,
 ':;:,.    .okxk0XXXXOc' .....,do:;.,lxddxxddl.   ..  .ck;,xkkkkkkkkkkkkkkkkkkkOKXNNNNKc.::.  .;l;..,:OKKXk'     'llllllll:,:llllllllllllc::llllllllllll;lXNXXXXXXXXXXXNKo:llllllc;:lllll:;cllllllllllllllc,.;lc';llllllllllllllllllllllllllllll:,:lllllllllllll;.:0XXNNNNNNNNNNNNNNNNNXKd. .;l:. .cooooooo;
 ':;:,.    .okxk0XXXXXXOc.  .;kOko:;ldxx00xkK0x:.  .   ck;,xkkkkkkkkkkkkkkkkkkkKNNNNNNo.;l,   .l:..';cx0X0;     .:lllllllc;;llllllllllllc;:llllllllllloc:kNXXXXXXXXXXXXNkccllllll:.'cllll:;cllllllllllllll;'':l,'clllllllllllllllllllllllllllllll;,clllllllllllll,.oXXNNNNNNNNNNXKKNNNX0Od' .:c,  .cooooooo;
 ,:;:,.    .okxk0XXXXXXXX0o,'lkxl:lx0KXN0olxkdxood,.   :x;;xkkkkkkkkkkkkkkkkOKKXNNNNNO''l:.   ,:...;;cOXKc      .clllllll;;clllllllllllc;:lllllllllllll;lKNXXXXXXXXXXXN0l:llllllc' .:llll;;llllllllllllllc;';c:';lcllllllllllllllllllllllllllllllc';lllllllllllllc.,0NNNNNNNNNNNXKXNNNXK0x'.,c:.  .:dddoooo;
.,:::,.    .okxxk0XXXXXXXXXKkl;,lxxxO0KkoldkOOxdKNKd.  ;d:ckkkkkkkkkkkkkkkkkOXNNNNNNXl.:l'    .. .,::kXXd.      ,lllllllc,:llllllllllll::llllllllllllc:;xNXXXXXXXXXXXNXd:cllllll;.  ;lllc,;lllllllllllllll:;:c,,clclllllllllllllllllllllllllllllc:,';lllllllllllll;.oNNNNNNNNNNNNNNNNNNNXx..;l;.  .:ddooodd:
.,:::,.    .dkxkOkxkKXXXXXXXXX0occoxxxl:d00KXXO0XXX0o;.':cdkkkkkkkkkkkkkkkkkKNX0do0Nk',lc.      .':;oKXO'      .:llllllc;;llllllllllll::lllllllllllll:':0NXXXXXXXXXXXNKoclcllllc.   'cccc,;llllllllllllllllcc:':lllllllllllllllllllllllllllllllc:;c:,;llllllllllllc.,0NNNNNNNNXK00XNNNNNKd..cc,.  .,odddddd:
.;:;:,.    .oxdo;..cKXXXXXXXXXXXKxl:cccdxxkKXXKkOXXxldkd;;okkkkkkkkkkkkkkkkOXNO,  :O:'clc.     ..;;c0XK:       .lllllll;,clllllllllll:;clllllllllllll;'oXXXXXXXXXXXXXNOlclccccl,    .;c:;';llllllllllllllllll,,clclllllllllllllllclllllllllllcc,';:,..',:ccllllllll;.lXNNNNNNNXXXKXNNNNX0o',lc.   .,odddddd:
.;'.;,.    .cd,..'c0XXXXXXXXXXXXXXKk:,cxxxxkOOdoONOox0KXKo:cdkkkkkkkkkkkkkkk0Xx'..',';cc:.    .',::kXXd.       ,llllll:,:lllllllllll:;clllllllllllllc;;xNXXXXXXXXXXXXNkcclccclc'.    ,l:'':lllllllllllllllll:,:lccllllllllllllclllllllllc:;;;;;;;::',:;,,,,;;;:clllc.,0NXNNNNX0O000KKXX0ko',l;.    'odddddd:
.;'.,,.     ,c,cddxOKXXXXXXXXXXXXXXXK:.,cxkkdoclkOdxKKOOOdoxocoxkkkkkkkkkkkOKXKx;,,.,ccc:.   ..';;lKXO,       .:lllllc,;lllllllllll:';llllllllllllllc:lONXXXXXXXXXXXXXxcclcccl;''    .,;;,cllllllllllllllllc,,ccllllllllllllllclccllc:;;;;;:ccllccccccllllcc:;;;;:cl,.xNXNNNNXKOkkkkkkkkkl.;c,.    'odddddd;
.;:;:,.     .lxxxkxOKXXXXXXXXXXXXXXXXl...,cdxc,:olcdkkOKKxkXXOo:lxkkkkkkkkkkKXNXOx:':ccc;.   .',;:kXXl        .clllll;,cllllllllllc;,,clllllllllllllccx0NXXXXXXXXXXXXXd:llcccl,,:.    ,l:,cllllllllllllllcl:,:lclllllllllllllllllc:;;;;:cllccccccccccccccccccllc:;,;;.cXNNNNNXKOkkkkkkkkkl':c'    .,odddddo,
.;:;:,.     .:xkxxk0XXXXXXXXXXXXXXXXXd.','.';:cooccd0XXXOdKXXOxdoclxkkkkkkk0XNNNNk;;cccc;.  .,';;lKXk'        'lllllc,:llllllllllc;:c;:lllllllllllll:lOKXXXXXXXXXXXXXXd:lccclc,,c'   'cc;,clllllllllcclcclc,,cccllccclllllllll:;;;;:cllclllccccllcccccccccccccccllc;;.'ONXNNNXKOkkkkkkkkkc':c'    .:ddddddl'
.;:::,.      'dkkxkKXXXXXXXXXXXXXXXXNx'';,,. .,cdxxxk0K0xO0Kkd0XXOoclxkkkkkkOKNNO:;ccccc,   ',,;;xK0l         ;llllc,,cllllllllll:;cl:;cllllllllllll:o0KXXXXXXXXXXXXXKd:lccllc,;l;. 'clc,,:lcclllllllcclll:':lcccccccllllcc:;;;;ccccccccclccccccccccccccccccccccccccl;.:KNXNNNX0kkkkkkkkkc'c:.... .cddddddl.
.;:::,.      .okkxkKXXXXXXXXXXXXXXXXNk,';;;'  ..;oxxxoloxk0kx0XXKxkOdclxkkkkkKNx,;cccccl,   ',,;ckOk,        .::,:l;':llllllllll:;cllc;:llllllllllll:o0KXXXXXXXXXXXXXKoc:;cllc;:l:..;llc,':lccllllllccccll;,ccccccccccc;;;;;:cll:;clcccccccccccccccccccccccccccccccccc..xNXNNNX0Okkkkkkkk:.,,......lddddddl.
.;:::,.      .okkkOKXXXKKXXXXXXXXXXXNO;';;;'  .. .;ooodxkOxxKK00xd0XX0dclxkkO0o,;ccccccl,  .',;;lkOd.         .',:;';llllllllllc;:llll;;llllllllllll:o0KXXXXXXXXXXXXX0oc:':lcccclc. ,llc;':lccccccccccccl:,;lccclllc:,,;:cclcccc::cccccccccccccccccccccccccccccccccccc'.oNXNNNNNX0Okkkkkk: ...  ..'looooddl.
.;:::;.      .lkkxk0XXXXXXXXXXXXXXXXNKc':;:,  .. ...;dkkxookkkOOdxXXXKOxoclxx:,:cccc;:cc,  .',;;okOc         .,cl:..clllllllllc;:lllll:;clllllllllc;.c0KXXXXXXXXXXXXX0lcc',clcclll, 'lll;':lcccccccllcccc,,clcccll:,,;clcccccclc;:cccccccccccccccccccccccccccccccccccl;'xNXXXK0OOOkkkkkkkl..'. ...,oooooodc.
.;:::,.  .   .ckkxx0XXXXXXXXXXXXXXXXXKc':::,  .  ..  .;lllddx0Kdlkkd0OxKXOoc,'ccccl;':lc'  .';;;kXO'        'cllc'.,llllllllll:;clllllc;:lllllll:,.  :0KXXXXXXXXXXXXX0l:l;.;lcllll;..cll:':lcccccccc:::;,';lccllc;';cccccccclll:,clccccccccccccccccccccccccccccccccccl:,oXXK0Okkkkkkkkkkkx;... ...:oooooooc.
.::::,.  .    ;xkxk0XXXXXXXXXXXXXXXXXXl':::;. .. ...   .;ldxxxo;;clOKkOKOxO0xc;;ccc,'cl:.  .':,c0Xo.      .;lll:. .:lllllllllc;:lllllll;;lllll:'.  ..:k0XXXXXXXXXXXXX0l:lc''clccll:..:ll:':lccccccc;;;,,'':lcll:,':ccccccccllc;';cccccccccccccccccccccccccccccccccccccl,:0XOkkkkkkkkkkkkkd'.'... ':cloooooc.
.::::,.  ..   ,xkkkOXXXXXXXXXXXXXXXXXXo';:::. .   ..   .l:,cdoclolxkodkdokKXKOxl;;c;':l;.  .,:,oX0;      'clll:.  .:lllllllll:;clllllllc:::;,'..',:l;:d0XXXXXXXXXXXXX0l:cc;.,cccclc. 'cl:';lcccccc;::,:c',lllc;'';cccccccllll;',ccccccccccccccccccccccccccccccccccccccl:,dNX0kkkkkkkkkkkkl..'.....';lccccc;.
'::::,.  .  . ,xkkkk0KKXXXXXXXXXXXXXXXd';;'''..   ...  .dl;c:,ckkkdcldldOKXKxkXXkc,'';l,   .;;,xXk.     'clllc.  .;;;:clclllc;:llllllllll:..,:clllll:;lkXXXXXXXXXXXXX0l:ccc,.;lcccc, .:l:.,lcccccccccll;':lc;,;,,cccccccllll;.,ccccccccccccccccccccccccccccccccccccccccc,:0N0kkkkkkkkkkkkc..'.....'''.......
'::::,.  .  . ,xkkkO0KXXXXXXXXXXXXXXXXx,,;'''..   ...  'dc:xxl;:olcdkddOOk0xo0X0k0kc'':'   .:,;OXo.     'cllc'  .;llc;;:clcl:;clllllccllll,.,lllllll:,:xXXXXXXXXXXXXXKl;lcl:..:lccl:. 'l:.'lccccccccclc''c:,;c:':lcccccclll;.'cccccccccccccccccccccccccccccccccccccccccl:,dXXK0Okkkkkkkkx:.''....'c,.  .. ..
'::::,.  .  . ,xkkkO0XXXXXXXXXXXXXXXXNk,,;,::.     ..  .oc:xkkxl;;okkxooololdOxlxXXXOl,.   .:,cKK:       .:c'   'clcclc;;;::;:lllllllcllllc..cllllllc,.oXXXXXXXXXXXXXKl:lccl,..:lclc. .;:.'ccccccccccl:.,c;:cc,,cccccccclc;..:lcccccccccccccccccccccccccccccccccccccccccl;:ONXK00Okkkkkkx;.''....'l:.  '....
'::::,.   . . ,xkkkO0000KXXXXXXXXXXXXNk;,::c:'     .'. .ccckkkkkkoccccoxdllclc:dKXXOk0Oc.  ';'oXO,        ..   .:lccccclc;,.':lllllllllllll:..:lllllc'.lKXXXXXXXOOKXXKl:lcclc. 'clll'  .;..clccccccclc,.:llll;':lcccccclc,'..:lccccccccccccccccccccccccccccccccccccccccccc,lXNNNX0kkkkkko. .'....'lc. .,.,,.
'::::,.    .. ,dkkO0000KXXXXXXXXXXXXXNO:;cccc'     .'. .:cckkkkkkkkd::ldxdc;lookOkxdoONX0l..,,dXk.             'cccccccccc;',,;clllcccccllcl;. ':clll,.:0XKXXXXX0dOXXKl;lccll;. ,cll;.  ...:lccccclc;. 'clllc,,ccccccclc'',.,ccccccccccccccccccccccccccccccccccccccccccccc;,xNXNXKOkkkkkl. ... ..'ll..::;c,.
'::::,.    .. .okkOO0KXXXXXXXXXXKKXXXX0c,cccc'     ... .:cckkkkkkkkkkdccodlokxolox00O00kdkOo,,kXd.            .:lcccccccl:,:lc;;clccccccccccc,   .;cl,.,kXKXXKXKXkd0XXo;cl:,',.  ;llc.  ...;lccccc;.  .;llll;':lcccllcc,';'.:cccccccccccccccccccccccccccccccccccccccccccccc,:0KO0KK0kkkk:........'lo;;lcll' 
.;:::,.   ... .okkkxxKXXXXXXXXXXXXXXXXKl;cccc'.  . ... .:cckkkkkkkkkkkkxc';dkxxxk0KxoddxxOXKOdokc             'cccccccccc;;cccc:;:ccccllcccccc,    .''..dXKKKKKKXKxxXXk::l:'.;,  .:ll'     'ccccc'   .,:lllc',cccclllc,';'.;lcccccccccccccccccccccccccccccccccccccccccccccc:'oX0kkkkkkkx;........,lolloool' 
.;:::,.    .  .okkkxk0XXXXXXXXXXXXXXXXKl,cccc,. .. ... .:o:cxkkkkkkkkkko,',,:dkxddl;cxOKKOk00Okd;             ;lcccccccc:,:lcccc:,:cccccccccccc,        lXKKKKKKKXOdOXKo;cccc:;.  .cl;     .:cc:.   .';cllc,,clccllcl:,,'.'ccccccccccccccccccccccccccccccccccccccccccccccccc,;OX0kkxkkkx,........,oooooool'.
.;:::,.       .lkkkxxOXXXXXXXXXXXXXXXXXo,cccc,. ......  :kd,ckkkkkkkkkl.':c:,,:oxdc:ok00kodddOKXOl.          .:ccccccccc;,clccccc;';cccccccccclc,       ;0XKKKKKKXKxdKXOc:ccccl;.  'lc.    .;c;.   .,;clcl:';lccccclc;,'..:cccccccccccccccccccccccccccccccccccccccccccccccccc'lXXKOkkkkd,........,oooooodl' 
.:::;'.....   .lkxxxxkKXXXXXXXXXXXXXXXXd,:c::,....... ..cko,:xkkkkkkx;.,ccccc:,,:cldxxxxl:ldxOXXXXk;.        'cccccccccc,;cccccccc:,,:ccccccclclc;.     .kXKKKKKKKX0okXKd;c::ccc;.  ,c'     .'    .',clclc,,cccccccl:,'..;ccccccccccccccccccccccccccccccccccccccccccccccccccc,,kKkkkkkkd'..... ..,loccoooc. 
.::;;;'..'..  .:xddkxk0XXXXXXXXXXXXXXXXd,:c:;;;'.... .,'cx::xkkkkkko'.;ccccccccc,.;oxxko:lxdd0XKOxxOOo'     .;ccccccccc:,:cccccccccc;',:cccccclccc:.    .oKKKKKKKKKXxo0X0c;:;:ccc,   ',.           .:cccl:';lccccclc,'..;cccccccccccccccccccccccccccccccccccccccccccccccccccc:'cKOkkkkko'........,c;;:looc. 
.:::;,,;,',. ..;dkxkxk0XXXXXXXXXXXXXXXXx;:c:;'.;:,..':'.lkc;dkkkkkc..:ccccccccccc..,:odldkxldkxkoo0XXX0o'   .cccccccccc;,cccccccccccc:,.';ccccccccl:.    :KKKKKKKKKX0oxKXk;::,,;cc,....            ,ccclc',cccccccl:...,ccccccccccccccccccccccccccccccc:cccccccccccccccccccccc,,kKkkkkkl.........;llooloo:. 
.:::::..:::,. .,dkxkxkKXXXXXXXXXXXXXXXXk;;c::' ..;;;,..,dkl,:dkkx:.':cccccccccccc,.,,.'cxxlcccdxdOXKKKKX0o'.,cccccccccc,;cccccccccccccc:'.',:ccccccl:.   'kXKKKKKKKKXklOXKo,,...,cc'.''.          .ccccl;.;lccccccc' .;cccccccccccccccccccccccccccccc:,:cccccccccccccccccccccc:.cKOkkkkc.........;oollooo:..
.:::::'..;lc. .,okxkxkKXXXXXXXXXXXXXXXXO;,:::;,..;c'. .cxko,cxkkl.'cc:ccccccccccc:..;;..;lccloxdxOkOKKOk0XKd:;:ccccccc:',ccccccccccccccccc;''',:clccc,.  .oKKKKKKKKKKKoo00O:..  ..::'.;,          ,ccccc''cccccccc,..;cccccccccccccccccccccccccccccl:,:cccccccccccccccccccccccc,'xKkkkk:..... ...,c:cccll:..
.:::::'...;c'..,okxkkxOKXXXXXXXXXXXXXXX0c,:::clccoc...,dkxl,cdkx,.,;,;:ccccccccccc,.':'...;oxkdldxkkdccxKKOddo:;:cccccc''cccccccccccccccccccc;,''';;.     ;0KKKKKKKKKKdcxkkl.     .'''.:;.       .:cccl;.;ccccccc,..:ccccccccccccccccccccccccccccccc,;ccccccccccccccccccccccccc:.cKOkkk:..... ...;l:;cccc;',
.:::::,....'...,lkxkkxx0XXXXXXXXXXXXXXXKl;:;;,;ccl:'..,dkkl;:cdl.',',;:ccccccccccc:..;;. .:lcldxxdool:okkdldOKKxc;:cccl;.;cccccccccccccccccccccc;'..      .lKKKKKKKKXKolxxkx,        ...:,       .:cccc''ccccccc,..:ccccccccccccccccccccccccccccccc;,:cccccccccccccccccccccccccc''xKkkx:.........;ooc;:lc::;
.:::::,..'..,..'cxxxxxdOXXXXXXXXXXXXXXXKo,;,,'';clc,;;';lxkl;:c,'::;;,';ccccccccccc' .;. .lOo;:clodxd::lclkKKKKOxoc;:cl:.'ccccccccccccccccccccccccc;.      .l0KKKK00Okccxkxkl.          .'.      .cccc;.,cccccc'..:cccccccccccccccccccccccccccccccc,,ccccccccccccccccccccccccccc:.c0Okx;.........;oool;:lc;'
.:::::;.....,,''cxkxkxdOXXXXXXXXXXXXXXXKo;;,,'';;:,,:cc,.;oxdo;':ccc;;:cccc;'.',:cc;. .. .lOdldocldxl:clcoO0kxxxOKKxc;:c,.,:ccc:;;:cccccccccccccccccc;'.     ,dkkkxxxxd:lxxxx:            ..     'cccc'.:ccccc'..:cccccccccccccccccccccccccccccccc:,:cccccccccccccccccccccccccccc''k0Od;.'...';,.;oooolc::;;
.;::::;..,,..'''cxxxxddOKXXXXXXXXXXXXXXXd;cc;''....,:::,,:lxx:.;ccccccccccc'     .';.    .lOock0x,'lddxdlcllodx0KKKX0o;,'..;:,,,;:,;cc:;;:ccccccccccccc'      .oxxxxxxxo:oxxkd,            ..    .;cc;.'cccc:...:ccccccccccccccccccccccccccccccccc,,ccccccccccccccccccccccccccccc:.c00d,.'',cc,..;llccclc:c:
.;::::;..,'...',cxoooddOKXXXXXXXXKKKOOKXd,,:,',,,;,,,,;';xkkl.'cccccccccccc;.       .    .lOock0O;  ,lo::cldxdx000K0xx0x;. .''';cdc.;cc:;,,;:cccccccc:,.       .lxxxxxxxocokxko.                  'cc'.;ccc:. .:ccccccccccccccccccccccccccccccccc:,;cccccccccccccccccccccccccccccc,,x0o'.,::,....:llcc:ccc;.
.;::::;... ....':c;:oxxOKXXXXXXXX00Kklcll'.',',:cll;,:,.:xkd,.:ccccccccccccc,             cOock0O;    .;odxxdloddOOdkKKKk,.,:,,;cl,'cccccc:,',:cccccc.          .cxxxxxxxocoxxxl.                 .c:.'ccc;. .:cccccccccccccccccccccccccccccccccc,,ccccccccccccccccccccccccccccccc:.c0o'.''......colcclol:,,
..'';::..'',,;,':c,cdxxkKXXXXXXXXXXXKOo:;'';;,;:cc;,:;''lkkc.,ccccccccccccccc,.           :kock0O:     .:dxxl;:lxdlxKKOl;;cc;,;lo,':cccccccc:,'.',:c,            .cxxxxxxxocoxxx:                  ,,.,cc,. .:cccccccccccccccccccccccccccccccccc:';cccccccccccccccccccccccccccccccc,'do,..;:::;',cc:lolccc;,
...,,;;,:looool:cdxxxdxOKXXXXXXXXXXXXXKKKx::;,;cccc;,,''lkd'.:cccccccccccccccc;.          :klck0Oc       .cdc:odocokkl;;cccc;:oc'':ccccccccccc:;.. .              .:dxxxxxxdclxxx:                 ...:c,  .:cccccccccccccccccccccccccccccc::;;,';cccccccccccccccccccc:cccccccccccc:';lc,','..';:ccool:codo:
'clol;,:c;,:lc;;:okxxxxOKXXXXXXXXXXXXXXXX0c;;:llol:'''''lk:.,ccccccccccccccccccc;.        ;klcO0Oc         .;odccclc,,:ccc:,:c'..,:cccccccccccccc:'.   ......       ;dxxxxxxdclxxx;                  ':'  .:cccccccccccccccccccccccccc:,''...'..;cccccccccccccccccccc:,:cccccccccccc:.,l'......',:loool:cllc
':clol:::.',,''',lxxxkkk0XXXXXXXXXXXXXXXXKl,;'.,,,.',,''oo..:ccccccccccccccccccccc;'.     ;kccO00l           ';c:,'';cccc;.,'   :l;,:cccccccccccccc:'   ..';::::c,.  'oxxxxxxdccxkd,                 ..  .:ccccccccccccccccccccc::;,,,,,;::::c:;:cccccccccccccccccccccccccccccccccccc;.,;;:::::,':lllllcclc:
,,,,,,',:cll::::;lxkkkkOKXXXXXXXXXXXXXXXXXo,,';:,..,,,'':..;cccccccccccccccccccccccc:,.   ,xccOO0l           .'...,::::;'',.  .l0X0l,,:cccccccccccccc,..    ..';:c;   .lxxxxxxdccdxd,                .  .:ccccc:;:ccccccccc:;;;,,;;;:ccccccccccccccccccccccccccccccccccccccccccccccccc,.;dddo:..';cccloooccl
,',:cc,,loloc;clccxkkkkkO0XXXXXXXXXXXXXXXXd:cllll,.,,,'...,:cccccccccccccc:;,..'',;:cc:,. 'dclOOOl.          ....;:::;,'..   .dKXKOo::,;cccccccccccccccc;'.      .'.   .;dxxxxxxl:lxd;                 ':cccc:,',:ccccc:;,,,,;:cccccccccccccccccccccc:;:cccccccccccccccccccccccccccccc:..lddc.....colllllllo
,,clloc;cllol;,:::dkkkxxk0XXXXXXXXXXXXXXXXkcclcc:;;;,;. .;::cccccccccccc:,'..  .''....',,.'lcokkkx,           .,',::,'..    ;kXX0dclOKkc,;ccccccccccccccccc;'..          .lxxxxxxo:cdx;               ':cccc;',;::::::;,,;:cccccccccccccccccccccc:;,;;;;:cccccccccccccccccccccccccccccc,.;do:...',coool:clll
lcccccl;.':c;',:::dkxkkkk0KXXXXXXXXXX0kxdxx:,::cc:cc,. .:::ccccccccccc;'.',::,..',:;'.    .l::xkkko.         .,;,''''.   ..ck0Oxllx0KOOkl,,;ccccccc;,''''',,;::;,'....     ,oxxxxxdc:dx;            .,cccccc::c:::;::::ccccccccccccccccccccccccc:;,,,,,,;::::cccccccccccccccccccccccccc;..,'.,;coddolooc:;;;
lllc;;;'..',',:cc:;cdkkkkO0KKXXXXXXXX0d:;;:,,:llc::,..,::::cccc:ccc:;'..','',,,,,''',;'   .cl':kkkkc        .'','.,;.  .,:oxxdllodxxkkkodkd:,;::,'.           ..;ccc:.      .cxxxxxxl:ld;           ,ccccccccccccccccccccccccccccccccccccccccccc;,,,,,,,,;;::cccccccccccccccccccc:;:ccc,.''..,lodddddddoc:cl
;,,',:cc;;;,,;ccc;.ckkxxxkO00KXXXXXXXXXK000c;llllc...;:::::::cccc:,...',,,,;:::::::,'''..  .o;.ckkkx,       .....'.    .;dxdo:cdxkOKKOdkKKK0o;'.            ...';c;.         .;dxxxxxd:co;         .cccccccccccccccccccccccccccccccccccccccccccc;..',,;:ccccccccccccccccccccccccc:,;ccc,.;:;'...:cloddoooodo
  .';:c::clc;;:cc;.;dxxxxO0K0KXXXXXXXXXXKXKo;cll:..':::::::::cc;'..';:::::::::::::::::,'..  'l'.lkkko.       .          .,cc:codxOKOxx0KKKKKk:'.   ..'....,::ccc;.             .lxxxxxdc:l;       .;cccccccccccccccccccccccccccccccccccccccccc:;,',;ccccccccccccccccccccccccccccc:';ccc''cc;.  'llc:;::clooo
..;cccc:',cl:,;cc;.'lolxkk0KKXXXXXXXXXXXXXKd;cc:' .::::::::::c;.  ':::::::::::::::::::::;'.  ,; 'dkkx:                 ',..;lodox0koxKKKKKKk;,dx:. ,:'..  .:cc:'                .cxxxxxx:;l'      ,cccccccccccccccccccccccccccccccccccccccccc:,.;cccccccccccccccccccccccccccccccc;';cc:.,llc. .:ool::l;.;ldd

`,
}